platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/alpine, tag: build}

run:
  path: ci/build.sh
  
inputs:
- name: libslz-ci
  path: ci

outputs:
- name: libslz
  path: out
